$diagLog = 'C:/Users/azuaje.MSMC/Documents/spanish-tblt/spanish_general_diagnostic_log.jsonl'
$sid = 's16-2026-05-23-family'
$cid = 'spanish_general'
$ts = '2026-05-23T00:00:00Z'

$lines = @(
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-orchestrator","round":null,"phase":"phase_neg3","severity":"Telemetry","event_type":"phase_entered","criterion":"01.9","details":"Phase -3: loaded spanish_general_profile.md (fresh, age=0 days)"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-orchestrator","round":null,"phase":"phase_neg2","severity":"Telemetry","event_type":"phase_entered","criterion":"01.9","details":"Phase -2: loaded class-profile.md (fresh, age=38 days, threshold=90)"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-orchestrator","round":null,"phase":"phase_neg1","severity":"Telemetry","event_type":"phase_entered","criterion":"01.9","details":"Phase -1: no quarantine files; activity-log path cached"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-orchestrator","round":null,"phase":"phase_0","severity":"Telemetry","event_type":"phase_entered","criterion":"01.9","details":"Phase 0: all session inputs elicited and validated"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-orchestrator","round":null,"phase":"phase_1","severity":"Telemetry","event_type":"phase_entered","criterion":"01.9","details":"Phase 1: PVS canonicalized (11 items); SCB assembled; 9-component hash inventory computed"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-orchestrator","round":null,"phase":"gate_a","severity":"Telemetry","event_type":"gate_a_confirmed","criterion":"F8.cross.2","details":"Gate A confirmed: SCB frozen; session.json written; round_1 status=not_started"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-activity-specialist","round":1,"phase":"round_1","severity":"Telemetry","event_type":"phase_entered","criterion":"01.9","details":"Round 1: tblt-activity-specialist invoked pipeline mode"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-activity-specialist","round":1,"phase":"round_1","severity":"Telemetry","event_type":"f3_passed","criterion":"F3","details":"F3 gap-pair contract validation passed on ab_representation.yaml"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-activity-specialist","round":1,"phase":"round_1","severity":"Telemetry","event_type":"f6_passed","criterion":"F6","details":"F6 passed: student_a.html, student_b.html, teacher_key.html — Check A and Check B"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-activity-specialist","round":1,"phase":"round_1","severity":"Telemetry","event_type":"phase_5b_write","criterion":"F8.act.4","details":"Phase 5b: log_write=ok; cross_course_feed_write=ok"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-inspector","round":1,"phase":"round_1","severity":"Telemetry","event_type":"inspector_evaluation","criterion":"03.5","details":"Inspector: kill=none; LayerA=(3,3,3,3) all_pass=true; LayerB=(2,3,3,3,suppressed) all_pass=true; total=23/24; verdict=CONVERGED"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-orchestrator","round":1,"phase":"gate_b","severity":"Telemetry","event_type":"gate_b_confirmed","criterion":"F8.cross.2","details":"Gate B confirmed: ADB extracted; round_1=passed_gate_B"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-pretask-specialist","round":2,"phase":"round_2","severity":"Telemetry","event_type":"phase_entered","criterion":"01.9","details":"Round 2: tblt-pretask-specialist invoked pipeline mode"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-pretask-specialist","round":2,"phase":"round_2","severity":"Telemetry","event_type":"f7_passed","criterion":"F7","details":"F7 coherence audit passed: 4/4 ADB keys covered, all rationales exceed 30 chars"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-pretask-specialist","round":2,"phase":"round_2","severity":"Telemetry","event_type":"f6_passed","criterion":"F6","details":"F6 passed: pretask_student.html, pretask_teacher.html"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-pretask-specialist","round":2,"phase":"round_2","severity":"Telemetry","event_type":"phase_5b_write","criterion":"F8.pre.3","details":"Phase 5b: log_write=ok; cross_course_feed_write=ok"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-orchestrator","round":2,"phase":"gate_c","severity":"Telemetry","event_type":"gate_c_confirmed","criterion":"F8.cross.2","details":"Gate C confirmed: round_2=passed_gate_C"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-reflective-specialist","round":3,"phase":"round_3","severity":"Telemetry","event_type":"phase_entered","criterion":"01.9","details":"Round 3: tblt-reflective-specialist invoked pipeline mode; writing_genre=formal_email; register_shift_pattern=informal_to_formal_verb_phrase (from frozen SCB, Q12)"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-reflective-specialist","round":3,"phase":"round_3","severity":"Telemetry","event_type":"f7_passed","criterion":"F7","details":"F7 coherence audit passed: 4/4 ADB keys covered, all rationales exceed 30 chars"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-reflective-specialist","round":3,"phase":"round_3","severity":"Telemetry","event_type":"f6_passed","criterion":"F6","details":"F6 passed: posttask.html (writing-task-container valid, register-shift-table present), posttask_teacher.html"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-reflective-specialist","round":3,"phase":"round_3","severity":"Telemetry","event_type":"phase_5b_write","criterion":"F8.ref.3","details":"Phase 5b: log_write=ok; cross_course_feed_write=ok"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-orchestrator","round":3,"phase":"gate_d","severity":"Telemetry","event_type":"gate_d_confirmed","criterion":"F8.cross.2","details":"Gate D confirmed: round_3=passed_gate_D; gate_d.status=passed"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-orchestrator","round":null,"phase":"phase_7","severity":"Telemetry","event_type":"pipeline_summary_card_generated","criterion":"07","details":"Phase 7: all integrity checks passed"}',
'{"timestamp":"2026-05-23T00:00:00Z","session_id":"s16-2026-05-23-family","course_id":"spanish_general","agent":"tblt-orchestrator","round":null,"phase":"phase_8","severity":"Telemetry","event_type":"session_completed","criterion":"ADR-0021","details":"Session complete; gates_passed=[A,B,C,D]; rejections_per_gate={B:0,C:0,D:0}; inspector_revision_count=0; f6_halt_count=0; f7_halt_count=0; reach_in_free=false"}'
)

foreach ($line in $lines) {
    Add-Content -Path $diagLog -Value $line -Encoding UTF8
}
Write-Output "Written $($lines.Count) diagnostic events to $diagLog"
